### ISSUE TITLE
Obvious way to search for all products available in a County

### ISSUE THREAD

**Issue by rhodges** [Ecotrust/OH4S_Proteins#123]
[feedback form] “While you can see the farms that distribute to a county, it would be nice to see a list of products available in that county.”
“I'm looking for growers in specific regions or counties as the first level of product purchases. I understand this is to be added but don't find this filter (yet?)”

QUESTION: Are they looking for 'growers with products available in the county' or 'growers that are physically within the county?'.

If only concerned with Availability, we can tweak the existing UI/Filters to offer this (I believe that the functionality is already there).

**Comment by ahedstrom** [comment]
I think they want the ability to do both -- search by availability in region AND producers physically within the county/counties
